package com.thierno.dynamodbgettingstarted.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@DynamoDBTable(tableName = "PaymentRequest") // This must be the same as in DynamoDB
@Data
public class PaymentRequest
{
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String orderId;

	@DynamoDBAttribute
	private String amount;

	@DynamoDBAttribute
	private String currency;

	@DynamoDBAttribute
	private String method;

	@DynamoDBAttribute
	private PaymentResponse response;
}
