package com.thierno.dynamodbgettingstarted.dto;

import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@DynamoDbBean
@Data
public class PaymentRequest
{
	private String id;

	@DynamoDbPartitionKey
	//	@DynamoDbAutoGeneratedUuid // manually setting it before save as the extention is not setting it in the object but rather in the payload getting sent to dy service
	public String getId()
	{
		return id;
	}

	@DynamoDbSortKey
	public String getCurrency()
	{
		return currency;
	}

	private String orderId;

	@DynamoDbSecondaryPartitionKey(indexNames = "orderId-index")
	public String getOrderId()
	{
		return orderId;
	}

	private String amount;

	private String currency;

	private String method;

	@DynamoDbSecondaryPartitionKey(indexNames = "method-index")
	public String getMethod()
	{
		return method;
	}

	private PaymentResponse response;
}
